import PDFDocument from "pdfkit";
import { pdfToBuffer } from "@/lib/delivery/package";
import { htmlToPlainText } from "@/lib/contracts/render";

export type ContractPdfInput = {
  title: string;
  contentHtml: string;
  documentId: string;
  signerName?: string;
  signerEmail?: string;
  signedAt?: Date;
  footerNote?: string;
};

/**
 * Build a printable PDF for a generated document (body from HTML as plain text + optional signature block).
 */
export async function buildContractPdfBuffer(input: ContractPdfInput): Promise<Buffer> {
  const body = htmlToPlainText(input.contentHtml);
  const doc = new PDFDocument({
    size: "LETTER",
    margin: 54,
    info: { Title: input.title, Subject: `Document ${input.documentId}` },
  });
  const width = doc.page.width - doc.page.margins.left - doc.page.margins.right;

  doc.font("Helvetica-Bold").fontSize(11).text("BRIGHTLINE PHOTOGRAPHY", { characterSpacing: 1.4 });
  doc.moveDown(0.8);
  doc.font("Helvetica-Bold").fontSize(16).fillColor("#111111").text(input.title, { width });
  doc.moveDown(1);
  doc.font("Helvetica").fontSize(10).fillColor("#333333").text(body || "(No body text.)", { width, align: "left" });

  if (input.signerName && input.signerEmail && input.signedAt) {
    doc.moveDown(2);
    doc.font("Helvetica-Bold").fontSize(11).text("Acceptance / electronic signature");
    doc.moveDown(0.4);
    doc.font("Helvetica").fontSize(10).text(`Name: ${input.signerName}`);
    doc.text(`Email: ${input.signerEmail}`);
    doc.text(`Signed: ${input.signedAt.toLocaleString("en-US", { dateStyle: "long", timeStyle: "short" })}`);
  }

  doc.moveDown(1.5);
  doc.font("Helvetica").fontSize(8).fillColor("#666666").text(
    input.footerNote ??
      `Document reference: ${input.documentId}. This PDF was generated by BRIGHTLINE Photography systems.`,
    { width }
  );

  return pdfToBuffer(doc);
}
